#!/usr/bin/env bash
# lib/build.sh — render Dockerfile + crontab and build the image.
#
# - Per-app venvs under /opt/venvs/<app>
# - Crontab built from apps[].schedule + apps[].entrypoint
# - Image tagged with the deployment name and the sha of the lockfile so
#   `nelly rollback` can switch back to a prior build.
# - Pass --dry-run to print the rendered Dockerfile and exit without building.
set -euo pipefail

DEPLOY_DIR="$1"; shift
LIB="$(dirname "$(realpath "$0")")"
# shellcheck source=common.sh
source "$LIB/common.sh"
# shellcheck source=config.sh
source "$LIB/config.sh"

DRY_RUN=0
while (( $# > 0 )); do
    case "$1" in
        --dry-run) DRY_RUN=1; shift ;;
        *) shift ;;
    esac
done

CONFIG="$DEPLOY_DIR/def/config.json"
DOCKERFILE_SRC="$DEPLOY_DIR/def/Dockerfile"
LOCKFILE="$DEPLOY_DIR/def/commits.lock.json"
APPS_DIR="$DEPLOY_DIR/apps"
BUILD_DIR="$DEPLOY_DIR/.build"
LOG_FILE="$DEPLOY_DIR/logs/build.log"

mkdir -p "$BUILD_DIR" "$(dirname "$LOG_FILE")"
exec > >(log_to "$LOG_FILE") 2>&1

require_cmd jq docker
validate_config "$DEPLOY_DIR"
[[ -f "$DOCKERFILE_SRC" ]] || die "Dockerfile not found: $DOCKERFILE_SRC"

IMAGE_NAME="$(jqget "$CONFIG" '.image_name')"
PROJECT_NAME="$(jqget "$CONFIG" '.container_name')"

# -----------------------------------------------------------------------------
# 1. Assemble crontab from per-app schedule + entrypoint.
# -----------------------------------------------------------------------------

CRONTAB="$BUILD_DIR/crontab"
{
    echo "# Generated by nelly; do not edit by hand."
    echo "SHELL=/bin/bash"
    echo "PATH=/usr/local/bin:/usr/bin:/bin"
    echo
} > "$CRONTAB"

mapfile -t APPS < <(jq -c '.apps[]' "$CONFIG")
SCHEDULED=0
for app in "${APPS[@]}"; do
    name="$(echo "$app"  | jq -r '.app_name')"
    sched="$(echo "$app" | jq -r '.schedule  // empty')"
    entry="$(echo "$app" | jq -r '.entrypoint // empty')"
    [[ -d "$APPS_DIR/$name" ]] || die "missing fetched app: $name (run: nelly fetch …)"

    if [[ -z "$sched" || -z "$entry" ]]; then
        warn "app $name has no schedule/entrypoint; installed but not scheduled"
        continue
    fi
    SCHEDULED=$((SCHEDULED+1))

    # Each cron line runs as root, chdir's to /home/apps/<app>, uses the app's
    # own venv, and logs to /var/log/nelly/<app>.log (bind-mounted).
    cmd="cd /home/apps/$name && /opt/venvs/$name/bin/python $entry"
    log="/var/log/nelly/$name.log"
    echo "$sched root /bin/bash -lc '$cmd' >> $log 2>&1" >> "$CRONTAB"
done
# /etc/cron.d files MUST end with a newline.
printf '\n' >> "$CRONTAB"

info "crontab assembled with $SCHEDULED scheduled app(s)"

# -----------------------------------------------------------------------------
# 2. Per-app pip install fragment.
# -----------------------------------------------------------------------------

REQS_FRAG="$BUILD_DIR/requirements.frag"
: > "$REQS_FRAG"
for app in "${APPS[@]}"; do
    name="$(echo "$app" | jq -r '.app_name')"
    echo "RUN python -m venv /opt/venvs/$name && /opt/venvs/$name/bin/pip install --no-cache-dir --upgrade pip" >> "$REQS_FRAG"
    if [[ -f "$APPS_DIR/$name/requirements.txt" ]]; then
        echo "RUN /opt/venvs/$name/bin/pip install --no-cache-dir -r /home/apps/$name/requirements.txt" >> "$REQS_FRAG"
    fi
done

# -----------------------------------------------------------------------------
# 3. System packages fragment.
# -----------------------------------------------------------------------------

PKG_FRAG="$BUILD_DIR/packages.frag"
mapfile -t PKGS < <(jq -r '.packages[]?' "$CONFIG")
: > "$PKG_FRAG"
if (( ${#PKGS[@]} > 0 )); then
    {
        echo "RUN apt-get update \\"
        echo " && apt-get install -y --no-install-recommends ${PKGS[*]} \\"
        echo " && rm -rf /var/lib/apt/lists/*"
    } > "$PKG_FRAG"
fi

# -----------------------------------------------------------------------------
# 4. Stage build context.
# -----------------------------------------------------------------------------

STAGE="$BUILD_DIR/ctx"
rm -rf "$STAGE"
mkdir -p "$STAGE"
cp -r "$APPS_DIR" "$STAGE/apps"
cp    "$CRONTAB"  "$STAGE/crontab"

awk -v pkgs="$(cat "$PKG_FRAG")" -v reqs="$(cat "$REQS_FRAG")" '
    /# NELLY: SYSTEM_PACKAGES/ { print pkgs; next }
    /# NELLY: APP_VENVS/       { print reqs; next }
    { print }
' "$DOCKERFILE_SRC" > "$STAGE/Dockerfile"

if (( DRY_RUN )); then
    info "dry-run: rendered Dockerfile follows"
    cat "$STAGE/Dockerfile"
    exit 0
fi

# -----------------------------------------------------------------------------
# 5. Tag with lockfile hash; build.
# -----------------------------------------------------------------------------

TAG="$(sha256sum "$LOCKFILE" 2>/dev/null | cut -c1-12)"
[[ -n "$TAG" ]] || TAG="latest"
DATE_TAG="$(date -u +%Y%m%d-%H%M%S)"
FULL_IMAGE="${IMAGE_NAME}:${TAG}"

info "building $FULL_IMAGE"
docker build \
    --pull \
    --build-arg PROJECT_NAME="$PROJECT_NAME" \
    -t "$FULL_IMAGE" \
    -t "${IMAGE_NAME}:${DATE_TAG}" \
    -t "${IMAGE_NAME}:latest" \
    "$STAGE"

info "built $FULL_IMAGE (also tagged :$DATE_TAG and :latest)"
echo "$FULL_IMAGE" > "$DEPLOY_DIR/def/last_image.txt"

# Record build history (kept short; rollback reads from here)
HISTORY="$DEPLOY_DIR/def/build_history.json"
[[ -f "$HISTORY" ]] || echo '[]' > "$HISTORY"
jq_inplace "$HISTORY" \
    --arg img "$FULL_IMAGE" --arg ts "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    '. + [{image: $img, built_at: $ts}] | .[-50:]'
