#!/usr/bin/env bash
# lib/build.sh — render Dockerfile + crontab and build the image.
#
# - Per-app venvs under /opt/venvs/<app>
# - Crontab built from apps[].schedule + apps[].entrypoint
# - Image tagged with the deployment name and the sha of the lockfile so
#   `nelly rollback` can switch back to a prior build.
# - Pass --dry-run to print the rendered Dockerfile and exit without building.
set -euo pipefail

DEPLOY_DIR="$1"; shift
LIB="$(dirname "$(realpath "$0")")"
# shellcheck source=common.sh
source "$LIB/common.sh"
# shellcheck source=config.sh
source "$LIB/config.sh"

DRY_RUN=0
while (( $# > 0 )); do
    case "$1" in
        --dry-run) DRY_RUN=1; shift ;;
        *) shift ;;
    esac
done

CONFIG="$DEPLOY_DIR/def/config.json"
DOCKERFILE_SRC="$DEPLOY_DIR/def/Dockerfile"
LOCKFILE="$DEPLOY_DIR/def/commits.lock.json"
APPS_DIR="$DEPLOY_DIR/apps"
BUILD_DIR="$DEPLOY_DIR/.build"
LOG_FILE="$DEPLOY_DIR/logs/build.log"

mkdir -p "$BUILD_DIR" "$(dirname "$LOG_FILE")"
exec > >(log_to "$LOG_FILE") 2>&1

require_cmd jq docker
validate_config "$DEPLOY_DIR"
[[ -f "$DOCKERFILE_SRC" ]] || die "Dockerfile not found: $DOCKERFILE_SRC"

IMAGE_NAME="$(jqget "$CONFIG" '.image_name')"
PROJECT_NAME="$(jqget "$CONFIG" '.container_name')"

# -----------------------------------------------------------------------------
# 1. Assemble crontab from per-app schedule + entrypoint.
# -----------------------------------------------------------------------------

CRONTAB="$BUILD_DIR/crontab"
{
    echo "# Generated by nelly; do not edit by hand."
    echo "SHELL=/bin/bash"
    echo "PATH=/usr/local/bin:/usr/bin:/bin"
    echo
} > "$CRONTAB"

mapfile -t APPS < <(jq -c '.apps[]' "$CONFIG")
SCHEDULED=0
for app in "${APPS[@]}"; do
    name="$(echo "$app"  | jq -r '.app_name')"
    sched="$(echo "$app" | jq -r '.schedule  // empty')"
    entry="$(echo "$app" | jq -r '.entrypoint // empty')"
    if [[ ! -d "$APPS_DIR/$name" ]]; then
        if (( DRY_RUN )); then
            warn "(dry-run) app $name not fetched yet — would normally die here"
        else
            die "missing fetched app: $name (run: nelly fetch …)"
        fi
    fi

    if [[ -z "$sched" || -z "$entry" ]]; then
        warn "app $name has no schedule/entrypoint; installed but not scheduled"
        continue
    fi
    SCHEDULED=$((SCHEDULED+1))

    # Each cron line invokes /usr/local/bin/nelly-run (baked into the image),
    # which runs the app's venv python with the entrypoint, captures the exit
    # code + duration, and appends one JSON line to
    # /var/log/nelly/<app>.metrics.jsonl (bind-mounted to host's logs/cron/).
    # Both $name and $entry are validated by lib/config.sh::validate_config
    # to contain only safe characters.
    echo "$sched root /usr/local/bin/nelly-run $name $entry" >> "$CRONTAB"
done
# /etc/cron.d files MUST end with a newline.
printf '\n' >> "$CRONTAB"

info "crontab assembled with $SCHEDULED scheduled app(s)"

# -----------------------------------------------------------------------------
# 2. Per-app pip install fragment.
# -----------------------------------------------------------------------------

REQS_FRAG="$BUILD_DIR/requirements.frag"
: > "$REQS_FRAG"
for app in "${APPS[@]}"; do
    name="$(echo "$app" | jq -r '.app_name')"
    echo "RUN python -m venv /opt/venvs/$name && /opt/venvs/$name/bin/pip install --no-cache-dir --upgrade pip" >> "$REQS_FRAG"
    if [[ -f "$APPS_DIR/$name/requirements.txt" ]]; then
        echo "RUN /opt/venvs/$name/bin/pip install --no-cache-dir -r /home/apps/$name/requirements.txt" >> "$REQS_FRAG"
    fi
done

# -----------------------------------------------------------------------------
# 3. System packages fragment.
# -----------------------------------------------------------------------------

PKG_FRAG="$BUILD_DIR/packages.frag"
mapfile -t PKGS < <(jq -r '.packages[]?' "$CONFIG")
: > "$PKG_FRAG"
if (( ${#PKGS[@]} > 0 )); then
    {
        echo "RUN apt-get update \\"
        echo " && apt-get install -y --no-install-recommends ${PKGS[*]} \\"
        echo " && rm -rf /var/lib/apt/lists/*"
    } > "$PKG_FRAG"
fi

# -----------------------------------------------------------------------------
# 4. Stage build context.
# -----------------------------------------------------------------------------

STAGE="$BUILD_DIR/ctx"
rm -rf "$STAGE"
mkdir -p "$STAGE/apps"
# Copy fetched apps into the stage. With --dry-run the apps dir may be empty
# (we haven't fetched yet); in that case the stage just gets the empty dir.
if [[ -d "$APPS_DIR" ]] && compgen -G "$APPS_DIR/*" >/dev/null; then
    cp -r "$APPS_DIR"/* "$STAGE/apps/"
fi
cp    "$CRONTAB"  "$STAGE/crontab"

# nelly-run wrapper: tiny shim that runs the app's venv python and records
# exit code + duration to /var/log/nelly/<app>.metrics.jsonl. Baked into the
# image so `nelly metrics` has data to aggregate. Written at build time so
# existing deployments work without re-scaffolding their template.
cat > "$STAGE/nelly-run" <<'NELLY_RUN_EOF'
#!/bin/bash
# nelly-run <app_name> <entrypoint_relpath>
#
# Runs the app's venv python with per-app secrets sourced in. Captures rc +
# duration to /var/log/nelly/<app>.metrics.jsonl. Rotates the log + metrics
# files when they exceed 10 MB (one .1 backup kept).
set +e
app="$1"; entry="$2"
log="/var/log/nelly/$app.log"
metrics="/var/log/nelly/$app.metrics.jsonl"
secrets_file="/etc/nelly/secrets/$app.env"
mkdir -p /var/log/nelly

# Rotate either file when it crosses 10 MB. Keep one previous generation.
MAX_BYTES="${NELLY_LOG_MAX_BYTES:-10485760}"
for f in "$log" "$metrics"; do
    if [ -f "$f" ]; then
        size="$(stat -c %s "$f" 2>/dev/null || echo 0)"
        if [ "$size" -gt "$MAX_BYTES" ]; then
            mv -f "$f" "$f.1" 2>/dev/null || true
        fi
    fi
done

# Secrets — cron clears its environment when dispatching a job, so we
# can't rely on `docker run --env-file` reaching the script here. Both
# the global file and the per-app file are bind-mounted read-only into
# /etc/nelly/ by lib/run.sh; we source them explicitly so the python
# process gets the env it expects. Per-app overrides global on conflict.
set -a
[ -f /etc/nelly/global.env ] && . /etc/nelly/global.env
[ -f "$secrets_file"        ] && . "$secrets_file"
set +a

ts_iso="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
ts_start="$(date +%s)"
"/opt/venvs/$app/bin/python" "/home/apps/$app/$entry" >> "$log" 2>&1
rc=$?
ts_end="$(date +%s)"
dur=$(( ts_end - ts_start ))
printf '{"ts":"%s","app":"%s","rc":%d,"duration_s":%d}\n' \
    "$ts_iso" "$app" "$rc" "$dur" >> "$metrics"
exit $rc
NELLY_RUN_EOF
chmod +x "$STAGE/nelly-run"

awk -v pkgs="$(cat "$PKG_FRAG")" -v reqs="$(cat "$REQS_FRAG")" '
    /# NELLY: SYSTEM_PACKAGES/ { print pkgs; next }
    /# NELLY: APP_VENVS/       { print reqs; next }
    { print }
' "$DOCKERFILE_SRC" > "$STAGE/Dockerfile"

# Substitute the base image with a config-pinned digest if provided. Pinning
# to a sha256 digest is the only way to get truly reproducible builds — the
# tag `python:3.11-slim` is mutable and what it resolves to changes over
# time. `nelly base-image-pin <name>` writes a fresh digest into config.
BASE_IMAGE="$(jqget "$CONFIG" '.base_image' '')"
if [[ -n "$BASE_IMAGE" ]]; then
    # Defense-in-depth: validate_config already rejects bad values.
    case "$BASE_IMAGE" in -*) die "base_image must not start with '-' (got: $BASE_IMAGE)";; esac
    info "pinning base image: $BASE_IMAGE"
    # Replace the first `FROM ...` line. Use awk to avoid sed-vs-special-char fights.
    awk -v img="$BASE_IMAGE" '
        !replaced && /^FROM / { print "FROM " img; replaced=1; next }
        { print }
    ' "$STAGE/Dockerfile" > "$STAGE/Dockerfile.new"
    mv "$STAGE/Dockerfile.new" "$STAGE/Dockerfile"
fi

# Install nelly-run regardless of whether the Dockerfile template had a
# placeholder for it — keeps older per-deployment templates working.
cat >> "$STAGE/Dockerfile" <<'DOCKERFILE_TAIL'

# Nelly run-wrapper for per-invocation metrics + per-app secret sourcing
# (appended by lib/build.sh).
COPY nelly-run /usr/local/bin/nelly-run
RUN  chmod +x  /usr/local/bin/nelly-run
DOCKERFILE_TAIL

if (( DRY_RUN )); then
    info "dry-run: rendered Dockerfile follows"
    cat "$STAGE/Dockerfile"
    exit 0
fi

# -----------------------------------------------------------------------------
# 5. Tag with lockfile hash; build.
# -----------------------------------------------------------------------------

TAG="$(sha256sum "$LOCKFILE" 2>/dev/null | cut -c1-12)"
[[ -n "$TAG" ]] || TAG="latest"
DATE_TAG="$(date -u +%Y%m%d-%H%M%S)"
FULL_IMAGE="${IMAGE_NAME}:${TAG}"

info "building $FULL_IMAGE"
docker build \
    --pull \
    --build-arg PROJECT_NAME="$PROJECT_NAME" \
    -t "$FULL_IMAGE" \
    -t "${IMAGE_NAME}:${DATE_TAG}" \
    -t "${IMAGE_NAME}:latest" \
    "$STAGE"

info "built $FULL_IMAGE (also tagged :$DATE_TAG and :latest)"
echo "$FULL_IMAGE" > "$DEPLOY_DIR/def/last_image.txt"

# Record build history (kept short; rollback reads from here)
HISTORY="$DEPLOY_DIR/def/build_history.json"
[[ -f "$HISTORY" ]] || echo '[]' > "$HISTORY"
jq_inplace "$HISTORY" \
    --arg img "$FULL_IMAGE" --arg ts "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    '. + [{image: $img, built_at: $ts}] | .[-50:]'
